// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdy9ZIkKcqcpmfoze7QbjqxWs6Yf3vZz0',
    appId: '1:608090304941:web:03f72387de609c9fe4f124',
    messagingSenderId: '608090304941',
    projectId: 'note-flutter-practice',
    authDomain: 'note-flutter-practice.firebaseapp.com',
    storageBucket: 'note-flutter-practice.appspot.com',
    measurementId: 'G-2PB2704MT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQx_-79a-rKj8WYHku4ktj55V1nETxmQ',
    appId: '1:608090304941:android:7d37d7b100a4d317e4f124',
    messagingSenderId: '608090304941',
    projectId: 'note-flutter-practice',
    storageBucket: 'note-flutter-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhu8tTWMBUQMi-1rKW3Setiq2feobR7uI',
    appId: '1:608090304941:ios:b8191f7c5347e194e4f124',
    messagingSenderId: '608090304941',
    projectId: 'note-flutter-practice',
    storageBucket: 'note-flutter-practice.appspot.com',
    iosBundleId: 'com.pnamacet.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhu8tTWMBUQMi-1rKW3Setiq2feobR7uI',
    appId: '1:608090304941:ios:b8191f7c5347e194e4f124',
    messagingSenderId: '608090304941',
    projectId: 'note-flutter-practice',
    storageBucket: 'note-flutter-practice.appspot.com',
    iosBundleId: 'com.pnamacet.mynotes',
  );
}
